branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-linux
    - cd $TRAVIS_BUILD_DIR
    - mkdir build 
    - cd build
    - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake -D TOBANTEAUDIO_ETL_ENABLE_COVERAGE:BOOL=TRUE ..
    - CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7 cmake --build . -- -j2
    - ctest -j2
    - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-7
    
  - &script-macOS
    - cd $TRAVIS_BUILD_DIR
    - mkdir build 
    - cd build
    - cmake ..
    - cmake --build . -- -j2
    - ctest -j2


matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      script: *script-macOS
      
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      script: *script-linux
