branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-coverage
    - cd $TRAVIS_BUILD_DIR
    - make coverage
    - bash <(curl -s https://codecov.io/bash) -f build_coverage/cov.info

  - &script-docs
    - cd $TRAVIS_BUILD_DIR
    - doxygen Doxyfile.in

  - &script-sanitizers
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=Release -DTOBANTEAUDIO_ETL_BUILD_ASAN=ON -DTOBANTEAUDIO_ETL_BUILD_UBSAN=ON -DTOBANTEAUDIO_ETL_BUILD_CPP20=ON
    - cmake --build . -- -j
    - ctest -j

matrix:
  include:
    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - ninja-build
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      script: *script-coverage

    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "deb https://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - ninja-build
            - clang++-12
      env:
        - MATRIX_EVAL="CC=clang-12 && CXX=clang++-12"
      script: *script-sanitizers

    - os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "deb https://apt.llvm.org/focal/ llvm-toolchain-focal-12 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - ninja-build
            - doxygen
            - graphviz
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      script: *script-docs
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: build-doc/html
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master

before_install:
  - eval "${MATRIX_EVAL}"
