branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-coverage
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake -D TOBANTEAUDIO_ETL_BUILD_COVERAGE:BOOL=TRUE .. -DCMAKE_BUILD_TYPE:STRING=Debug -DTOBANTEAUDIO_ETL_BUILD_CPP20=ON
    - cmake --build . -- -j
    - ctest -j
    - bash <(curl -s https://codecov.io/bash)

  - &script-docs
    - cd $TRAVIS_BUILD_DIR
    - doxygen Doxyfile.in

  - &script-sanitizers
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=Release -DTOBANTEAUDIO_ETL_BUILD_ASAN=ON -DTOBANTEAUDIO_ETL_BUILD_UBSAN=ON -DTOBANTEAUDIO_ETL_BUILD_CPP20=ON
    - cmake --build . -- -j
    - ctest -j

  - &script-macOS
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=Release -DTOBANTEAUDIO_ETL_BUILD_CPP20=ON
    - cmake --build . -- -j2
    - ctest -j2
    - rm -rf *
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug -DTOBANTEAUDIO_ETL_BUILD_CPP20=ON
    - cmake --build . -- -j2
    - ctest -j2

matrix:
  include:
    - os: osx
      osx_image: xcode12
      script: *script-macOS

    - os: osx
      osx_image: xcode11.6
      script: *script-macOS

    - os: linux
      dist: focal
      addons:
        apt:
          packages:
            - ninja-build
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      script: *script-coverage

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - ninja-build
            - clang++-9
      env:
        - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
      script: *script-sanitizers

    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
            - sourceline: "deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - ninja-build
            - doxygen
            - graphviz
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
      script: *script-docs
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: build-doc/html
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master

before_install:
  - eval "${MATRIX_EVAL}"
