branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-linux
    - cd $TRAVIS_BUILD_DIR
    - mkdir build 
    - cd build
    - cmake ..
    - cmake --build . 
    
  - &script-macOS
    - cd $TRAVIS_BUILD_DIR
    - mkdir build 
    - cd build
    - cmake ..
    - cmake --build . 


matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      script: *script-macOS
      
    - os: linux
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      script: *script-linux
