# GENERAL
version: 0.2.0.{build}
branches:
  only:
    - master
image:
  - Visual Studio 2017
clone_folder: c:\projects\source

# BUILD
build_script:
- cmd: >-
    # DEBUG
    mkdir build_debug

    cd build_debug

    cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE:STRING=Debug
    
    cmake --build . --config "Debug"

    cd ..

    # RELEASE
    mkdir build_release

    cd build_release

    cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE:STRING=Release
    
    cmake --build . --config "Release"

    cd ..

# TEST    
test_script:
- cmd: >-
    # DEBUG
    cd build_debug
    
    ctest -C Debug

    cd ..

    # RELEASE
    cd build_release

    ctest -C Release