# GENERAL
version: 0.1.0.{build}
branches:
  only:
    - master
image:
  - Visual Studio 2017
clone_folder: c:\projects\source

# BUILD
build_script:
- cmd: >-
    mkdir build

    cd build

    cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE:STRING=Release
    
    cmake --build . --config "Release"

# TEST    
test_script:
- cmd: ctest -C Release