name: ARM C++17

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: tobante/arm-gcc:9.3
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build examples project (C++17, Debug)
        run: ARM=1 DEBUG=1 make -C examples clean all

      - name: Build examples project (C++17, Release)
        run: ARM=1 make -C examples clean all
