name: ARM C++20

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    container:
      image: alpine:edge
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add make gcc-arm-none-eabi g++-arm-none-eabi newlib-arm-none-eabi grep --no-cache
          grep --version
          arm-none-eabi-g++ --version

      - name: Build examples project (C++20, Debug)
        run: ARM=1 CXXSTD=20 DEBUG=1 make -C examples clean all

      - name: Build examples project (C++20, Release)
        run: ARM=1 CXXSTD=20 make -C examples clean all
