name: ARM C++23

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: alpine:edge
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add make gcc-arm-none-eabi newlib-arm-none-eabi grep --no-cache
          grep --version
          arm-none-eabi-g++ --version

      - name: Build examples project (C++23, Debug)
        run: ARM=1 CXXSTD=2b DEBUG=1 make -C examples clean all

      - name: Build examples project (C++23, Release)
        run: ARM=1 CXXSTD=2b make -C examples clean all
