name: ARM C++20

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: tobante/arm-gcc:9.3
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build examples project (C++20, Debug)
        run: ARM=1 CXXSTD=2a DEBUG=1 make -C examples clean all

      - name: Build examples project (C++20, Release)
        run: ARM=1 CXXSTD=2a make -C examples clean all