name: ASAN

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      
      - name: cmake configure
        run: cmake -S . -B cmake-build-asan -D TETL_BUILD_ASAN=ON

      - name: dump config
        run: cat cmake-build-asan/compile_commands.json

      - name: cmake build
        run: cmake --build cmake-build-asan -- -j

      - name: run tests
        run: export CTEST_OUTPUT_ON_FAILURE=1; cd cmake-build-asan; ctest -VV; cd -
