name: AVR C++17

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: tobante/avr-gcc:9.2
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build examples project (C++17, Debug)
        run: AVR=1 DEBUG=1 make -C examples clean all

      - name: Build examples project (C++17, Release)
        run: AVR=1 make -C examples clean all

