name: AVR C++17

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: alpine:edge
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add cmake ninja make gcc-avr avr-libc --no-cache
          avr-g++ --version

      - name: Configure CMake
        run: cmake -S . -B build -G "Ninja Multi-Config" -D CMAKE_TOOLCHAIN_FILE=cmake/Toolchain-atmega328p.cmake -D CMAKE_CXX_STANDARD=17 -D TETL_BUILD_WERROR=ON

      - name: Build tests -- Debug
        run: cmake --build build --config Debug

      - name: Build tests -- Release
        run: cmake --build build --config Release
