name: AVR C++20

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: alpine:edge
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add cmake ninja make gcc-avr avr-libc --no-cache
          avr-g++ --version

      - name: Build examples project (C++20, Debug)
        run: AVR=1 CXXSTD=20 DEBUG=1 make -C examples clean all

      - name: Build examples project (C++20, Release)
        run: AVR=1 CXXSTD=20 make -C examples clean all

      - name: Build tests
        run: |
          cmake -S . -B build -G "Ninja Multi-Config" -D CMAKE_TOOLCHAIN_FILE=cmake/Toolchain-atmega328p.cmake -D TETL_BUILD_CPP20=ON -D TETL_BUILD_WERROR=ON
          cmake --build build --config Debug --target tests/stack/all
          cmake --build build --config Debug --target tests/stdexcept/all
          cmake --build build --config Debug --target tests/string/all
          cmake --build build --config Debug --target tests/string_view/all
          cmake --build build --config Debug --target tests/tuple/all
          cmake --build build --config Debug --target tests/utility/all
          cmake --build build --config Debug --target tests/variant/all
          cmake --build build --config Debug --target tests/vector/all
          cmake --build build --config Debug --target tests/version/all
          cmake --build build --config Release --target tests/stack/all
          cmake --build build --config Release --target tests/stdexcept/all
          cmake --build build --config Release --target tests/string/all
          cmake --build build --config Release --target tests/string_view/all
          cmake --build build --config Release --target tests/tuple/all
          cmake --build build --config Release --target tests/utility/all
          cmake --build build --config Release --target tests/variant/all
          cmake --build build --config Release --target tests/vector/all
          cmake --build build --config Release --target tests/version/all
