name: AVR C++20

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: alpine:edge
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add make gcc-avr avr-libc --no-cache
          avr-g++ --version

      - name: Build examples project (C++20, Debug)
        run: AVR=1 CXXSTD=20 DEBUG=1 make -C examples clean all

      - name: Build examples project (C++20, Release)
        run: AVR=1 CXXSTD=20 make -C examples clean all
