name: Clang-Tidy

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: add LLVM Key
        run: sudo wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

      - name: add LLVM Repo
        run: sudo add-apt-repository 'deb http://apt.llvm.org/jammy/   llvm-toolchain-jammy-15  main'

      - name: update
        run: sudo apt update -y

      - name: install clang-tidy
        run: sudo apt install -y clang-15 clang-tidy-15 ninja-build

      - name: cmake configure
        run: CC=clang-15 CXX=clang++-15 cmake -S . -G Ninja -B cmake-build-tidy -DCMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_STANDARD=20 -D TETL_BUILD_WERROR=ON

      - name: clang-tidy check
        run: BUILD_DIR=cmake-build-tidy make tidy-check
