name: Clang-Tidy

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [17, 20, 23]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update
        run: sudo apt update -y

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15 all

      - name: CMake configure
        run: >
          cmake -S .
          -G "Unix Makefiles"
          -B cmake-build-tidy
          -D CMAKE_BUILD_TYPE=Debug
          -D CMAKE_C_COMPILER="clang-15"
          -D CMAKE_CXX_COMPILER="clang++-15"
          -D CMAKE_CXX_STANDARD="${{ matrix.cxx }}"
          -D TETL_BUILD_WERROR=ON

      - name: Clang-Tidy check
        run: CLANG_VERSION="-15" BUILD_DIR=cmake-build-tidy make tidy-check
