name: Clang-Tidy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: add LLVM Key
        run: sudo wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

      - name: add LLVM Repo
        run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/   llvm-toolchain-focal-12  main'

      - name: update
        run: sudo apt update -y

      - name: install clang-tidy
        run: sudo apt install -y clang-12 clang-tidy-12 ninja-build

      - name: cmake configure
        run: CC=clang-12 CXX=clang++-12 cmake -S . -G Ninja -B cmake-build-tidy -DCMAKE_BUILD_TYPE=Debug -D TETL_BUILD_WERROR=ON

      - name: clang-tidy check
        run: BUILD_DIR=cmake-build-tidy make tidy-check
