name: Clang -Weverything

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [17, 20, 23]
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: add LLVM Key
        run: sudo wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

      - name: add LLVM Repo
        run: sudo add-apt-repository 'deb http://apt.llvm.org/jammy/   llvm-toolchain-jammy-15  main'

      - name: update
        run: sudo apt update -y

      - name: install clang-tidy
        run: sudo apt install -y clang-15 clang-tidy-15 ninja-build

      - name: CMake configure
        run: >
          cmake -S . -G "Ninja Multi-Config" -B build
          -D CMAKE_C_COMPILER="clang-15"
          -D CMAKE_CXX_COMPILER="clang++-15"
          -D CMAKE_CXX_STANDARD="${{ matrix.cxx }}"
          -D TETL_BUILD_WERROR=ON
          -D TETL_BUILD_WEVERYTHING=ON

      - name: CMake build -- Debug
        run: cmake --build build --config Debug

      - name: CMake build -- Release
        run: cmake --build build --config Release
