name: Doxygen

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install doxygen
        run: sudo apt install -y doxygen

      - name: Generate HTML documentation
        run: doxygen Doxyfile

      - name: Pushes to documentation repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.DOXYGEN_PUSH_TOKEN }}
        with:
          source-directory: "build-doxygen/html"
          destination-github-username: "tobanteEmbedded"
          destination-repository-name: "tetl-docs"
          user-email: tobanteEmbedded@gmail.com
          target-branch: main
