name: AVR Freestanding

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: alpine:edge
    strategy:
      matrix:
        cxx: [17, 20, 23]
      fail-fast: false
    name: C++${{ matrix.cxx }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add cmake ninja make gcc-avr avr-libc --no-cache
          avr-g++ --version

      - name: Configure CMake
        run: >
          cmake -S .
          -B build
          -G "Ninja Multi-Config"
          -D CMAKE_TOOLCHAIN_FILE=cmake/toolchain/atmega328p.cmake
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx }}
          -D TETL_BUILD_WERROR=ON

      - name: Build tests -- Release
        run: cmake --build build --config Release
