name: ARM Freestanding

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: alpine:edge
    strategy:
      matrix:
        cxx: [17, 20, 23]
      fail-fast: false
    name: C++${{ matrix.cxx }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add make gcc-arm-none-eabi g++-arm-none-eabi newlib-arm-none-eabi grep --no-cache
          grep --version
          arm-none-eabi-g++ --version

      - name: Build examples projects (Debug)
        run: ARM=1 CXXSTD=${{ matrix.cxx }} DEBUG=1 make -C examples clean all

      - name: Build examples projects (Release)
        run: ARM=1 CXXSTD=${{ matrix.cxx }} make -C examples clean all
