name: GCC C++20

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install ninja-build
        run: sudo apt install -y ninja-build

      - name: Install CMake
        run: |
          sudo apt remove --purge cmake
          hash -r
          sudo snap install cmake --classic
          cmake --version

      - name: CMake configure
        run: cmake -S . -G "Ninja Multi-Config" -B build -D CMAKE_CXX_STANDARD=20 -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build build --config Debug

      - name: Run all tests -- Debug
        run: ctest --test-dir build -C Debug

      - name: CMake build -- Release
        run: cmake --build build --config Release

      - name: Run all tests -- Release
        run: ctest --test-dir build -C Release
