name: Clang C++17

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download git submodules
        run: git submodule update --recursive --init

      - name: Install ninja-build
        run: sudo apt install -y ninja-build

      - name: CMake configure -- Debug
        run: CC=clang-10 CXX=clang++-10 cmake -S . -G Ninja -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build cmake-build-debug

      - name: Run tests -- Debug
        run: cd cmake-build-debug; ctest; cd -

      - name: CMake configure -- Release
        run: CC=clang-10 CXX=clang++-10 cmake -S . -G Ninja -B cmake-build-release -DCMAKE_BUILD_TYPE=Release -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Release
        run: cmake --build cmake-build-release

      - name: Run tests -- Release
        run: cd cmake-build-release; ctest; cd -
