name: Clang C++23

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: add LLVM Key
        run: sudo wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

      - name: add LLVM Repo
        run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/   llvm-toolchain-focal-13  main'

      - name: update
        run: sudo apt update -y

      - name: install clang-tidy
        run: sudo apt install -y clang-13 clang-tidy-13 ninja-build

      - name: CMake configure -- Debug
        run: CC=clang-13 CXX=clang++-13 cmake -S . -G Ninja -B cmake-build-debug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=23 -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: CC=clang-13 CXX=clang++-13 cmake --build cmake-build-debug

      - name: Run tests -- Debug
        run: cd cmake-build-debug; ctest -VV; cd -

      - name: CMake configure -- Release
        run: CC=clang-13 CXX=clang++-13 cmake -S . -G Ninja -B cmake-build-release -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=23 -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Release
        run: CC=clang-13 CXX=clang++-13 cmake --build cmake-build-release

      - name: Run tests -- Release
        run: cd cmake-build-release; ctest -VV; cd -
