name: Clang C++17

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install ninja-build
        run: sudo apt install -y ninja-build

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: CMake configure
        run: cmake -S . -G "Ninja Multi-Config" -B build -D CMAKE_CXX_STANDARD=17 -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build build --config Debug

      - name: Run all tests -- Debug
        run: ctest --test-dir build -C Debug

      - name: CMake build -- Release
        run: cmake --build build --config Release

      - name: Run all tests -- Release
        run: ctest --test-dir build -C Release
