name: GCC C++23

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: alpine:edge
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: apk add git build-base cmake ninja --no-cache

      - name: Configure CMake
        run: cmake -S . -B build -G "Ninja Multi-Config" -D CMAKE_CXX_STANDARD=23 -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build build --config Debug

      - name: Run all tests -- Debug
        run: ctest --test-dir build -C Debug

      - name: CMake build -- Release
        run: cmake --build build --config Release

      - name: Run all tests -- Release
        run: ctest --test-dir build -C Release
