name: Linux X64

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        config:
          [
            { cc: gcc-10, cxx: g++-10 },
            { cc: gcc-11, cxx: g++-11 },
            { cc: gcc-12, cxx: g++-12 },
            { cc: clang-12, cxx: clang++-12 },
            { cc: clang-13, cxx: clang++-13 },
            { cc: clang-14, cxx: clang++-14 },
          ]
        cxx_std: [17, 20, 23]
      fail-fast: false
    runs-on: ubuntu-22.04
    name: Linux x64 ${{ matrix.config.cc }} c++${{ matrix.cxx_std }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Update APT
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build
          which ${{ matrix.config.cc }}

      - name: Install ${{ matrix.config.cc }}
        run: sudo apt install -y ${{ matrix.config.cc }}

      - name: CMake configure (clang)
        run: >
          cmake -S .
          -B build
          -G "Ninja Multi-Config"
          -D CMAKE_C_COMPILER=${{ matrix.config.cc }}
          -D CMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx_std }}
          -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build build --config Debug

      - name: Run all tests -- Debug
        run: ctest --test-dir build -C Debug --output-on-failure

      - name: CMake build -- Release
        run: cmake --build build --config Release

      - name: Run all tests -- Release
        run: ctest --test-dir build -C Release --output-on-failure
