name: macOS C++17

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install ninja
        run: brew install ninja

      - name: CMake configure
        run: cmake -S . -B build -G "Ninja Multi-Config" -D CMAKE_CXX_STANDARD=17 -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build build --config Debug

      - name: Run tests -- Debug
        run: cd build; ctest -VV -C Debug; cd -

      - name: CMake build -- Release
        run: cmake --build build --config Release

      - name: Run tests -- Release
        run: cd build; ctest -VV -C Release; cd -
