name: macOS C++17

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: CMake configure -- Debug
        run: cmake -S . -B cmake-build-debug -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build cmake-build-debug --config Debug

      - name: Run tests -- Debug
        run: cd cmake-build-debug; ctest -VV; cd -

      - name: CMake configure -- Release
        run: cmake -S . -B cmake-build-release -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Release
        run: cmake --build cmake-build-release --config Release

      - name: Run tests -- Release
        run: cd cmake-build-release; ctest -VV; cd -
