name: MSP430 C++23

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: alpine:edge
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add git --no-cache
          apk add make gcc-msp430-elf newlib-msp430-elf grep --no-cache
          grep --version
          msp430-elf-g++ --version

      - name: Build examples project (C++23, Debug)
        run: MSP430=1 CXXSTD=2b DEBUG=1 make -C examples clean all

      - name: Build examples project (C++23, Release)
        run: MSP430=1 CXXSTD=2b make -C examples clean all
