name: Sanitize ASAN

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        cxx: [17, 20, 23]
      fail-fast: false
    name: C++${{ matrix.cxx }}
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: Update APT
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15 all

      - name: cmake configure
        run: >
          cmake -S .
          -B build
          -G Ninja
          -D CMAKE_BUILD_TYPE=Debug
          -D CMAKE_C_COMPILER=clang-15
          -D CMAKE_CXX_COMPILER=clang++-15
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx }}
          -D TETL_BUILD_ASAN=ON

      - name: dump config
        run: cat build/compile_commands.json

      - name: cmake build
        run: cmake --build build

      - name: run tests
        run: ctest -VV --test-dir build -C Debug --output-on-failure
