name: UBSAN

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: check out code
        uses: actions/checkout@v3

      - name: Update APT
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build

      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 15 all

      - name: cmake configure
        run: CC=clang-15 CXX=clang++-15 cmake -S . -B cmake-build-ubsan -D TETL_BUILD_UBSAN=ON -D CMAKE_CXX_STANDARD=20

      - name: dump config
        run: cat cmake-build-ubsan/compile_commands.json

      - name: cmake build
        run: CC=clang-15 CXX=clang++-15 cmake --build cmake-build-ubsan -- -j

      - name: run tests
        run: export CTEST_OUTPUT_ON_FAILURE=1; cd cmake-build-ubsan; ctest -VV; cd -
