name: UBSAN

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: add LLVM Key
        run: sudo wget --no-check-certificate -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -

      - name: add LLVM Repo
        run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/   llvm-toolchain-focal-13  main'

      - name: update
        run: sudo apt update -y

      - name: install clang-tidy
        run: sudo apt install -y clang-13 clang-tidy-13 ninja-build

      - name: cmake configure
        run: CC=clang-13 CXX=clang++-13 cmake -S . -B cmake-build-ubsan -D TETL_BUILD_UBSAN=ON

      - name: dump config
        run: cat cmake-build-ubsan/compile_commands.json

      - name: cmake build
        run: CC=clang-13 CXX=clang++-13 cmake --build cmake-build-ubsan -- -j

      - name: run tests
        run: export CTEST_OUTPUT_ON_FAILURE=1; cd cmake-build-ubsan; ctest -VV; cd -
