name: Windows C++23

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install ninja
        run: choco install ninja

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake configure
        run: cmake -S . -B build -G "Ninja Multi-Config" -D CMAKE_CXX_STANDARD=23 -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build build --config "Debug"

      - name: Run tests -- Debug
        run: cd build; ctest -C Debug; cd -

      - name: CMake build -- Release
        run: cmake --build build --config "Release"

      - name: Run tests -- Release
        run: cd build; ctest -C Release; cd -
