name: Windows C++20
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: windows-2019
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download git submodules
        run: git submodule update --recursive --init

      - name: CMake configure -- Debug
        run: cmake -S . -B cmake-build-debug -G "Visual Studio 16 2019" -D TOBANTEAUDIO_ETL_BUILD_CPP20=ON -D TOBANTEAUDIO_ETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build cmake-build-debug --config "Debug"

      - name: Run tests -- Debug
        run: cd cmake-build-debug; ctest -C Debug; cd -

      - name: CMake configure -- Release
        run: cmake -S . -B cmake-build-release -G "Visual Studio 16 2019" -D TOBANTEAUDIO_ETL_BUILD_CPP20=ON -D TOBANTEAUDIO_ETL_BUILD_WERROR=ON

      - name: CMake build -- Release
        run: cmake --build cmake-build-release --config "Release"

      - name: Run tests -- Release
        run: cd cmake-build-release; ctest -C Release; cd -

