name: Windows X64

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        cxx: [17, 20, 23]
      fail-fast: false
    name: C++${{ matrix.cxx }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install ninja
        run: choco install ninja

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: CMake configure
        run: >
          cmake -S .
          -B build
          -G "Ninja Multi-Config"
          -D CMAKE_CXX_STANDARD=${{ matrix.cxx }}
          -D TETL_BUILD_WERROR=ON

      - name: CMake build -- Debug
        run: cmake --build build --config "Debug"

      - name: Run tests -- Debug
        run: ctest --test-dir build -C Debug --output-on-failure

      - name: CMake build -- Release
        run: cmake --build build --config "Release"

      - name: Run tests -- Release
        run: ctest --test-dir build -C Release --output-on-failure
